# Generated by Django 5.0.6 on 2024-06-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_alter_film_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='trailer',
            field=models.URLField(blank=True, default='', max_length=1500, null=True),
        ),
    ]
