# Generated by Django 5.0.6 on 2024-06-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_alter_film_trailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='star1',
        ),
        migrations.RemoveField(
            model_name='film',
            name='star2',
        ),
        migrations.RemoveField(
            model_name='film',
            name='star3',
        ),
        migrations.RemoveField(
            model_name='film',
            name='star4',
        ),
        migrations.AddField(
            model_name='film',
            name='director_pic',
            field=models.URLField(default='', max_length=500),
        ),
    ]
