# Generated by Django 5.0.6 on 2024-06-03 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_remove_film_star1_remove_film_star2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_name', models.CharField(max_length=250)),
                ('star_pic', models.URLField(max_length=500)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='films.film')),
            ],
        ),
    ]
